### ISSUE TITLE
Add Ruby version pill

### ISSUE THREAD

**Issue by CuriousFurBytes** [lucasqueiroz/powerline-pills-zsh#14]
# Description

There should be a pill containing Ruby's version.

**Comment by bestest-mensch** [comment]
Hi @lucasqueiroz, do you mind if I work on this?

**Comment by CuriousFurBytes** [comment]
> Hi @lucasqueiroz, do you mind if I work on this?

Oh I'm so sorry, I didn't see your comment before doing it.
Thank you for your support though. If you want to work on other version "pills" that would be great!
