### ISSUE TITLE
Error when run ./install.sh

### ISSUE THREAD

**Issue by mateusz-piotrowski** [lucasqueiroz/powerline-pills-zsh#8]
Welcome,
When I run ./install.sh I have the following error:
mkdir: /themes: Permission denied
cp: /themes: Permission denied

-------------------------------------------------

I copy manual theme to my themes folder, but when I reload terminal window
I have the following error:
Traceback (most recent call last):
ruby: No such file or directory -- /lib/powerline_pills.rb (LoadError)

**Comment by CuriousFurBytes** [comment]
Have you tried running the install command with sudo? Maybe your user doesn't have the permissions to move/write to the zsh folders.
I'll also update the installation instructions to include a manual installation procedure in case the automatic one fails.

**Comment by mateusz-piotrowski** [comment]
I manually copy this theme file and re-run install and it completed successfully.

**Comment by CuriousFurBytes** [comment]
Thanks for the info. I will add information about the manual installation soon.
