### ISSUE TITLE
Installation - Mac OS

### ISSUE THREAD

**Issue by raphaelmro** [lucasqueiroz/powerline-pills-zsh#9]
First of all, congrats for the awesome theme.
I've installed the nerd fonts from brew on Mac and chose the automatic path for the powerline-pills-zsh.
The result was a mess here, lol:
![screen shot 2018-03-05 at 09 35 09](https://user-images.githubusercontent.com/1179732/36975521-1e06100e-2059-11e8-8b06-51c157f50a9b.JPG)

Could you help me?

**Comment by CuriousFurBytes** [comment]
Have you selected the fonts on your terminal configuration? It looks like you're using iTerm 2, but not sure. If it's iTerm 2, go to
Preferences (CMD + ,) -> Profiles -> Select your profile or create a new one -> Text -> Change Font -> Select the font you downloaded

Please tell me if it doesn't work for you, and the terminal you're using so I can help you :)

**Comment by raphaelmro** [comment]
It works! Thanks, bro!

**Comment by CuriousFurBytes** [comment]
No problem :) Glad you liked it
